use clap::{ App, Arg, SubCommand }; 

fn main() {
    let matches = App::new("tic_tac_toe")
        .version("0.1.0")
        .about("tic tac toe game wwith reforcement learning AI")
        .author("LAURENT Louis")
        .subcommand(SubCommand::with_name("play")
            .about("Game launcher command")
            .arg(Arg::with_name("console")
                .short("c")
                .long("cmd")
                .long("console")
                .required_unless("graphic")
                .conflicts_with("graphic")
                .help("Launch game inside the console")
            )
            .arg(Arg::with_name("graphic")
                .short("g")
                .long("gui")
                .long("graphic")
                .required_unless("console")
                .conflicts_with("console")
                .help("Launch game in graphic mode")
            )
            .arg(Arg::with_name("ai_path")
                .short("p")
                .long("ai-path")
                .value_name("AI_PATH")
                .required(true)
                .takes_value(true)
                .help("Path to where AI files are store")
            )
        )
        .subcommand(SubCommand::with_name("train")
            .about("Train AI with reforcement learning. The result if this command is the creation of a file with the trained AI")
            .arg(Arg::with_name("again_agent")
                .long("again-agent")
                .required_unless("again_random")
                .conflicts_with("again_random")
                .help("Train AI again another AI. The experience of both are use for training")
            )
            .arg(Arg::with_name("again_random")
                .long("again-random")
                .required_unless("again_agent")
                .conflicts_with("again_agent")
                .help("Train AI again random moves")
            )
            .arg(Arg::with_name("GAMES_TO_PLAY")
                .required(true)
                .index(1)
                .help("Number of game to play")
            )
        )
        .get_matches();
}
